<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="jiangtaodeMacBook-Pro.local" ignored="0" name="TestDebug" tests="4" failures="2" timestamp="01 一月 2020 13:29:22 GMT" time="0.028" errors="0">
  <testcase name="testOneOne" time="0.002" classname="com.jt.qa.TestOne">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.jt.qa.TestOne.testOneOne(TestOne.java:24)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testOneOne -->
  <testcase name="testOneTwo" time="0.0" classname="com.jt.qa.TestOne">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.jt.qa.TestOne.testOneTwo(TestOne.java:29)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testOneTwo -->
  <testcase name="testOneTwo" time="0.0" classname="com.jt.qa.TestOne"/>
  <testcase name="testOneTwo" time="0.0" classname="com.jt.qa.TestOne"/>
</testsuite> <!-- TestDebug -->
