<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="jiangtaodeMacBook-Pro.local" ignored="0" name="Command line test" tests="5" failures="2" timestamp="31 十二月 2019 17:18:52 GMT" time="0.03" errors="0">
  <testcase name="testOne" time="0.002" classname="com.jt.qa.TestOne">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.jt.qa.TestOne.testOne(TestOne.java:24)
at com.jt.App.main(App.java:19)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testOne -->
  <testcase name="testTwo" time="0.0" classname="com.jt.qa.TestOne">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.jt.qa.TestOne.testTwo(TestOne.java:29)
at com.jt.App.main(App.java:19)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testTwo -->
  <testcase name="testTwo" time="0.0" classname="com.jt.qa.TestOne"/>
  <testcase name="testTwo" time="0.001" classname="com.jt.qa.TestOne"/>
  <testcase name="testThree" time="0.0" classname="com.jt.qa.TestThress"/>
</testsuite> <!-- Command line test -->
